### ISSUE TITLE
Cannot use dotbot-yaourt plugin with ./install

### ISSUE THREAD

**Issue by OxSon** [niklas-heer/dotbot-yaourt#3]
In order to get the yaourt plugin to work, I have to run, from my dotfiles repo, `dotbot/bin/dotbot -p dotbot-yaourt/yaourt.py -c packages.conf.yaml` rather than `./install -p dotbot-yaourt/yaourt.py -c packages.conf.yaml`. What am I doing wrong?

The output I get is the same as if `./install` was running my default config, then this on `stderr`:

```bash
usage: dotbot [-h] [-Q] [-q] [-v] [-d BASEDIR] [-c CONFIGFILE] [-p PLUGIN]
              [--disable-built-in-plugins] [--plugin-dir PLUGIN_DIR]
              [--no-color] [--version]
dotbot: error: argument -c/--config-file: expected one argument
```

**Comment by OxSon** [comment]
Issue was resolved [here](https://github.com/ajlende/dotbot-pacaur/issues/6)

**Comment by niklas-heer** [comment]
@OxSon sorry for the late answer but I'm no longer using Arch/Manjaro so this repo is kind of abandoned. 
Glad to hear you found a solution!
